---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# tabicl    

TabICL: A Tabular Foundation Model for In-Context Learning on Large Data with reticulate

## Setup 
```r
pak::pak("frankiethull/tabicl")

tabicl::create_tabicl_env()
tabicl::use_tabicl_env()
tabicl::install_tabicl_dependencies()
```

## Example

```{r example}
library(tabicl)
library(rsample)
tabicl::use_tabicl_env()

corn_data <- maize::corn_data

corn_splits <- initial_validation_split(corn_data)
train <- training(corn_splits)
validate <- validation(corn_splits)
test <- testing(corn_splits)
```

### Classification

TabICL currently supports classification only. 
```{r}
fit_cls <- tabicl_fit(
  train |> dplyr::select(-type), train$type
)

class_preds <- tabicl_predict(fit_cls, test |> dplyr::select(-type))

class_preds |> head()
```

```{r}
class_probs <- tabicl_predict(fit_cls, test |> dplyr::select(-type), type = "proba")

class_probs |> head()
```